START TRANSACTION;

-- Support large custom item IDs in augment sockets (for example 1,152,012,001).
-- MEDIUMINT UNSIGNED max is 16,777,215 and causes MySQL 1264 on save.

ALTER TABLE `inventory`
	MODIFY COLUMN `augment_one` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_two` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_three` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_four` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_five` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_six` INT(11) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `sharedbank`
	MODIFY COLUMN `augment_one` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_two` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_three` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_four` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_five` INT(11) UNSIGNED NOT NULL DEFAULT 0,
	MODIFY COLUMN `augment_six` INT(11) UNSIGNED NOT NULL DEFAULT 0;

COMMIT;
