// Auto-generated by tools/generate_augments.py — DO NOT EDIT
// Generated: 2026-03-06 17:15:04
// Defines ID ranges and lookup helpers for the augment merge system.
#pragma once

#include <cstdint>

namespace AugMergeData {

// Leveling weapon augs: 27 families × 5 levels
static constexpr uint32_t LEVEL_AUG_BASE     = 200100;
static constexpr int      LEVEL_AUG_FAMILIES = 27;

// Endgame stat augs: 7 families × 5 levels
static constexpr uint32_t STAT_AUG_BASE      = 200300;
static constexpr int      STAT_AUG_FAMILIES  = 7;

// Endgame proc augs: 5 families × 5 levels
static constexpr uint32_t PROC_AUG_BASE      = 200400;
static constexpr int      PROC_AUG_FAMILIES  = 5;

static constexpr int LEVELS_PER_FAMILY = 5;
static constexpr int MAX_AUG_LEVEL     = 5;
static constexpr int TOTAL_FAMILIES     = 39;

// Merge Catalysts — index 0 = L1→L2, 1 = L2→L3, 2 = L3→L4, 3 = L4→L5
static constexpr uint32_t CATALYST_IDS[]  = { 200500, 200501, 200502, 200503 };
static constexpr int      NUM_CATALYSTS   = 4;

static constexpr uint32_t FORGEMASTER_CONTAINER_ID = 200510;

// Decode an item ID into (family, level). Returns false if not a mergeable aug.
inline bool GetAugInfo(uint32_t item_id, int& out_family, int& out_level) {
    if (item_id >= LEVEL_AUG_BASE && item_id < LEVEL_AUG_BASE + LEVEL_AUG_FAMILIES * LEVELS_PER_FAMILY) {
        uint32_t offset = item_id - LEVEL_AUG_BASE;
        out_family = static_cast<int>(offset / LEVELS_PER_FAMILY);
        out_level  = static_cast<int>(offset % LEVELS_PER_FAMILY) + 1;
        return true;
    }
    if (item_id >= STAT_AUG_BASE && item_id < STAT_AUG_BASE + STAT_AUG_FAMILIES * LEVELS_PER_FAMILY) {
        uint32_t offset = item_id - STAT_AUG_BASE;
        out_family = static_cast<int>(offset / LEVELS_PER_FAMILY) + LEVEL_AUG_FAMILIES;
        out_level  = static_cast<int>(offset % LEVELS_PER_FAMILY) + 1;
        return true;
    }
    if (item_id >= PROC_AUG_BASE && item_id < PROC_AUG_BASE + PROC_AUG_FAMILIES * LEVELS_PER_FAMILY) {
        uint32_t offset = item_id - PROC_AUG_BASE;
        out_family = static_cast<int>(offset / LEVELS_PER_FAMILY) + LEVEL_AUG_FAMILIES + STAT_AUG_FAMILIES;
        out_level  = static_cast<int>(offset % LEVELS_PER_FAMILY) + 1;
        return true;
    }
    return false;
}

// Encode a family + level back to an item ID. Returns 0 if invalid.
inline uint32_t GetItemID(int family, int level) {
    if (level < 1 || level > MAX_AUG_LEVEL) return 0;
    if (family < LEVEL_AUG_FAMILIES) {
        return LEVEL_AUG_BASE + family * LEVELS_PER_FAMILY + (level - 1);
    }
    int f = family - LEVEL_AUG_FAMILIES;
    if (f < STAT_AUG_FAMILIES) {
        return STAT_AUG_BASE + f * LEVELS_PER_FAMILY + (level - 1);
    }
    f -= STAT_AUG_FAMILIES;
    if (f < PROC_AUG_FAMILIES) {
        return PROC_AUG_BASE + f * LEVELS_PER_FAMILY + (level - 1);
    }
    return 0;
}

// Get the required catalyst item ID for merging from current_level to current_level+1.
// Returns 0 if already at max level.
inline uint32_t GetRequiredCatalyst(int current_level) {
    if (current_level >= 1 && current_level < MAX_AUG_LEVEL) {
        return CATALYST_IDS[current_level - 1];
    }
    return 0;
}

// Check if an item is a catalyst. Returns the target merge level (2-5) or 0.
inline int GetCatalystTier(uint32_t item_id) {
    for (int i = 0; i < NUM_CATALYSTS; i++) {
        if (item_id == CATALYST_IDS[i]) return i + 2;
    }
    return 0;
}

} // namespace AugMergeData

