//Mail and Chat Channels
N(OP_Buddy),
N(OP_ChannelAnnounceJoin),
N(OP_ChannelAnnounceLeave),
N(OP_Ignore),
N(OP_Mail),
N(OP_MailboxChange),
N(OP_MailDeliveryStatus),
N(OP_MailHeader),
N(OP_MailHeaderCount),
N(OP_MailLogin),
N(OP_MailNew),
N(OP_MailSendBody),
N(OP_EdgeDPS = 0x1337),
N(OP_EdgeStatLabel = 0x1338),
N(OP_InitBanker = 0x1339),
